In [1]:
#linear search:
import random
import time
def search(arr, n, x): 
  
    for i in range (0, n): 
        if (arr[i] == x): 
            return i; 
    return -1; 
  
# Driver Code 
size=int(input("enter the no of inputs"))
arr = [random.randint(0,100)for i in range(size)]
print(arr)
x = 10;  
result = search(arr,size, x) 
if(result == -1): 
    print("Element is not present in array") 
else: 
    print("Element is present at index", result); 


enter the no of inputs3
[90, 21, 58]
Element is not present in array


In [2]:
#binary search
def binary_search(item_list,item):
    first = 0
    last = len(item_list)-1
    found = False
    while( first<=last and not found):
        mid = (first + last)//2
        if item_list[mid] == item :
            found = True
        else:
            if item < item_list[mid]:
                last = mid - 1
            else:
                first = mid + 1	
    return found
    
print(binary_search([1,2,3,5,8], 6))
print(binary_search([1,2,3,5,8], 5))

False
True


In [3]:
#selection sort
import random
import time
size=int(input("enter the size"))
arr=[random.randint(0,100) for i in range(size)]
sta=time.time()
for i in range(0,len(arr)):
    min=i
    for j in range(i+1,len(arr)):
        if arr[min]>arr[j]:
            min=j   
    temp=arr[i]
    arr[i]=arr[min]
    arr[min]=temp
    print("sorted array",arr)
print("final array",arr)
end=time.time()
print(end-sta)

enter the size3
sorted array [7, 9, 41]
sorted array [7, 9, 41]
sorted array [7, 9, 41]
final array [7, 9, 41]
0.015393495559692383


In [4]:
#bubble sort
import numpy as np
import time
import random
n=int(input("Enter the number of inputs"))
a=[random.randint(0,100) for i in range(n)]
s=time.time()
print(a)
for i in range(0,n):
    for j in range(n-i-1):
        if a[j]>a[j+1]:
            temp=a[j+1]
            a[j+1]=a[j]
            a[j]=temp
    print(a)
end=time.time()
print(end-s)
print(a)

Enter the number of inputs5
[100, 1, 82, 22, 30]
[1, 82, 22, 30, 100]
[1, 22, 30, 82, 100]
[1, 22, 30, 82, 100]
[1, 22, 30, 82, 100]
[1, 22, 30, 82, 100]
0.003998756408691406
[1, 22, 30, 82, 100]


In [5]:
#insertion
import time
import numpy as np
import random
s=time.time()
def insertionSort(arr): 
    for i in range(1, len(arr)): 
        key = arr[i] 
        j = i-1
        while j >=0 and key < arr[j] : 
                arr[j+1] = arr[j] 
                j -= 1 
                arr[j+1] = key 
                print(arr)

arr=np.random.randint(0,100,5)
insertionSort(arr) 
e=time.time()
print(e-s)
print ("Sorted array is:") 
print(arr)

[42 32 93 60 95]
[32 42 93 60 95]
[32 42 60 93 95]
0.0
Sorted array is:
[32 42 60 93 95]


In [8]:
import numpy as np
def mergeSort(arr): 
    if len(arr) >1: 
        mid = len(arr)//2
        L = arr[:mid]   
        R = arr[mid:] 
        mergeSort(L) 
        mergeSort(R) 
        i = j = k = 0
          
        
        while i < len(L) and j < len(R): 
            if L[i] < R[j]: 
                arr[k] = L[i] 
                i+=1
            else: 
                arr[k] = R[j] 
                j+=1
            k+=1
          
        while i < len(L): 
            arr[k] = L[i] 
            i+=1
            k+=1
          
        while j < len(R): 
            arr[k] = R[j] 
            j+=1
            k+=1
  
# Code to print the list 
def printList(arr): 
    for i in range(len(arr)):         
        print(arr[i],end="\n") 
    print() 
  
# driver code to test the above code 
if __name__ == '__main__': 
    arr = [59,34,10,76,44]
    print ("Given array is ",end="\n")  
    printList(arr) 
    mergeSort(arr) 
    print("Sorted array is:",end="\n") 
    printList(arr) 

Given array is 
59
34
10
76
44

Sorted array is:
10
34
44
59
76



In [12]:
def partition(array, start, end):
    pivot = array[start]
    low = start + 1
    high = end

    while True:
    
        while low <= high and array[high] >= pivot:
            high = high - 1

        # Opposite process of the one above
        while low <= high and array[low] <= pivot:
            low = low + 1
        if low <= high:
            array[low], array[high] = array[high], array[low]
            # The loop continues
        else:
            # We exit out of the loop
            break

    array[start], array[high] = array[high], array[start]

    return high

In [13]:
def quick_sort(array, start, end):
    if start >= end:
        return

    p = partition(array, start, end)
    quick_sort(array, start, p-1)
    quick_sort(array, p+1, end)

In [14]:
array = [29,99,27,41,66,28,44,78,87,19,31,76,58,88,83,97,12,21,44]

quick_sort(array, 0, len(array) - 1)
print(array)

[12, 19, 21, 27, 28, 29, 31, 41, 44, 44, 58, 66, 76, 78, 83, 87, 88, 97, 99]


In [15]:
def insertionSort(b): 
    for i in range(1, len(b)): 
        up = b[i] 
        j = i - 1
        while j >=0 and b[j] > up:  
            b[j + 1] = b[j] 
            j -= 1
        b[j + 1] = up      
    return b      
              
def bucketSort(x): 
    arr = [] 
    slot_num = 10 # 10 means 10 slots, each 
                  # slot's size is 0.1 
    for i in range(slot_num): 
        arr.append([]) 
          
    # Put array elements in different buckets  
    for j in x: 
        index_b = int(slot_num * j)  
        arr[index_b].append(j) 
      
    # Sort individual buckets  
    for i in range(slot_num): 
        arr[i] = insertionSort(arr[i]) 
          
    # concatenate the result 
    k = 0
    for i in range(slot_num): 
        for j in range(len(arr[i])): 
            x[k] = arr[i][j] 
            k += 1
    return x 
  
# Driver Code 
x = [0.897, 0.565, 0.656, 
     0.1234, 0.665, 0.3434]  
print("Sorted Array is") 
print(bucketSort(x)) 

Sorted Array is
[0.1234, 0.3434, 0.565, 0.656, 0.665, 0.897]


In [16]:
def heapify(arr, n, i): 
    largest = i  # Initialize largest as root 
    l = 2 * i + 1     # left = 2*i + 1 
    r = 2 * i + 2     # right = 2*i + 2 
  
    # See if left child of root exists and is 
    # greater than root 
    if l < n and arr[i] < arr[l]: 
        largest = l 
  
    # See if right child of root exists and is 
    # greater than root 
    if r < n and arr[largest] < arr[r]: 
        largest = r 
  
    # Change root, if needed 
    if largest != i: 
        arr[i],arr[largest] = arr[largest],arr[i]  # swap 
  
        # Heapify the root. 
        heapify(arr, n, largest) 
  
# The main function to sort an array of given size 
def heapSort(arr): 
    n = len(arr) 
  
    # Build a maxheap. 
    for i in range(n, -1, -1): 
        heapify(arr, n, i) 
  
    # One by one extract elements 
    for i in range(n-1, 0, -1): 
        arr[i], arr[0] = arr[0], arr[i]   # swap 
        heapify(arr, i, 0) 
  
# Driver code to test above 
arr = [ 12, 11, 13, 5, 6, 7] 
heapSort(arr) 
n = len(arr) 
print ("Sorted array is") 
for i in range(n): 
    print ("%d" %arr[i])

Sorted array is
5
6
7
11
12
13


In [17]:
def countingSort(arr, exp1): 
  
    n = len(arr) 
  
    # The output array elements that will have sorted arr 
    output = [0] * (n) 
  
    # initialize count array as 0 
    count = [0] * (10) 
  
    # Store count of occurrences in count[] 
    for i in range(0, n): 
        index = (arr[i]/exp1) 
        count[ (index)%10 ] += 1
  
    # Change count[i] so that count[i] now contains actual 
    #  position of this digit in output array 
    for i in range(1,10): 
        count[i] += count[i-1] 
  
    # Build the output array 
    i = n-1
    while i>=0: 
        index = (arr[i]/exp1) 
        output[ count[ (index)%10 ] - 1] = arr[i] 
        count[ (index)%10 ] -= 1
        i -= 1
  
    # Copying the output array to arr[], 
    # so that arr now contains sorted numbers 
    i = 0
    for i in range(0,len(arr)): 
        arr[i] = output[i] 
  
# Method to do Radix Sort 
def radixSort(arr): 
  
    # Find the maximum number to know number of digits 
    max1 = max(arr) 
  
    # Do counting sort for every digit. Note that instead 
    # of passing digit number, exp is passed. exp is 10^i 
    # where i is current digit number 
    exp = 1
    while max1/exp > 0: 
        countingSort(arr,exp) 
        exp *= 10
  
# Driver code to test above 
arr = [ 170, 45, 75, 90, 802, 24, 2, 66] 
radixSort(arr) 
  
for i in range(len(arr)): 
    print(arr[i])

TypeError: list indices must be integers or slices, not float

In [18]:
#0-1 knapsack problem
def knap(a,wt,value,no): 
    if no == 0 :
        return 0
    if a == 0 : 
        return 0
    if (wt[no-1]>a): 
        return knap(a,wt,value,no-1) 
  
    else: 
        return max(value[no-1] + knap(a-wt[no-1],wt,value,no-1), 
                   knap(a,wt,value,no-1)) 


In [19]:
value=[100,180,200] #the values
wt=[25,60,65] #the weights
a = 50 #maximum weight
no = len(value) #finding the no of items
print(knap(a,wt,value,no))

100


In [20]:
def fract_knapsack(W, wt, val,n): 
    result=0
    if n == 0 or W == 0 : 
        return 0
    if (wt[n-1] > W): 
        val[n-1]=(W/wt[n-1])*val[n-1]
        wt[n-1]=W
        result=result+val[n-1]
        W=W-wt[n-1]
        return result
    else: 
        result= max(val[n-1] + fract_knapsack(W-wt[n-1], wt, val, n-1), fract_knapsack(W, wt, val, n-1)) 
        return result

In [21]:
val = [40,30,50,10] 
wt= [2,5,10,5]
val, wt = zip(*sorted(zip(val, wt)))
val=list(val)
wt=list(wt)
W = 16
n = len(val) 
print (fract_knapsack(W,wt,val,n)) 

114.0


In [22]:
def LCS(X , Y): 
    m = len(X) 
    n = len(Y) 
  
    L = [[None]*(n+1) for i in range(m+1)] 

    for i in range(m+1): 
        for j in range(n+1): 
            if i == 0 or j == 0 : 
                L[i][j] = 0
            elif X[i-1] == Y[j-1]: 
                L[i][j] = L[i-1][j-1]+1
            else: 
                L[i][j] = max(L[i-1][j] , L[i][j-1])
    return L[m][n] 
  

In [23]:
X = "PRERTBANSK"
Y = "ESETLAITBANK"
print ("Longest Common Subsequence ", LCS(X, Y))

Longest Common Subsequence  6


In [24]:
def LCSubStr(X, Y):  
      
    m = len(X) 
    n = len(Y) 
  
    L = [[None]*(n+1) for i in range(m+1)] 
    result = 0 
  
    for i in range(m + 1): 
        for j in range(n + 1): 
            if (i == 0 or j == 0): 
                L[i][j] = 0
            elif (X[i-1] == Y[j-1]): 
                L[i][j] = L[i-1][j-1] + 1
                result = max(result, L[i][j]) 
            else: 
                L[i][j] = 0
    return result 

In [25]:
X='graduation'
Y='gradschool'
print ("Longest Common Substring ", LCSubStr(X, Y))

Longest Common Substring  4


In [26]:
def SJF(arr,time):
    n=len(arr)
    time_taken=[0]*n
    result=0
    time,arr = zip(*sorted(zip(time, arr)))
    arr=list(arr)
    time=list(time)
    print("Order of job execution is",arr)
    for i in range (0,n):
        time_taken[i]=time_taken[i-1]+time[i]
        result+=time_taken[i]
    return result

In [27]:
arr=['a','b','c']
time=[20,4,10]
print("Time taken is",SJF(arr,time))

Order of job execution is ['b', 'c', 'a']
Time taken is 52


In [29]:
def JobScheduling(arr,t):
    n = len(arr)
    for i in range(n): 
        for j in range(n - 1 - i): 
            if arr[j][2] < arr[j + 1][2]: 
                arr[j], arr[j + 1] = arr[j + 1], arr[j] 
    result = [False] * t 
    job = ['0'] * t     
    for i in range(len(arr)): 
        for j in range(arr[i][1] - 1, -1,-1): 
            if result[j] is False: 
                result[j] = True
                job[j] = arr[i][0] 
                break
    print(job) 

In [30]:
arr = [['a', 2, 100], 
       ['b', 1, 19], 
       ['c', 2, 27], 
       ['d', 1, 25], 
       ['e', 3, 15]] 
print("Following is maximum profit sequence of jobs") 
JobScheduling(arr, 3)

Following is maximum profit sequence of jobs
['c', 'a', 'e']


In [31]:
def matrix_chain_mult(p, n):
    m = [[0 for x in range(n)] for x in range(n)] 
    for i in range(1, n): 
        m[i][i] = 0
    for L in range(2, n): 
        for i in range(1, n-L+1): 
            j = i+L-1
            for k in range(i, j): 
                q = m[i][k] + m[k+1][j] + p[i-1]*p[k]*p[j] 
                if m[i][j]!=0 & q < m[i][j]: 
                    m[i][j] = q 
                else:
                    m[i][j]=q
  
    return m[1][n-1] 

In [32]:
p = [1, 2, 3 ,4] 
n= len(p) 
  
print("Minimum number of multiplications is", matrix_chain_mult(p,n))


Minimum number of multiplications is 18


In [33]:
def knapsack(W, wt, val): 
    n=len(val)
    L = [[0 for x in range(W + 1)] for x in range(n + 1)] 
    for i in range(n + 1): 
        for w in range(W + 1): 
            if i == 0 or w == 0: 
                L[i][w] = 0
            elif wt[i-1] <= w: 
                L[i][w] = max(val[i-1] + L[i-1][w-wt[i-1]],  L[i-1][w]) 
            else: 
                L[i][w] = L[i-1][w] 
    return L[n][W] 


In [34]:
val = [40,30,50,10] 
wt = [2,5,10,5] 
W = 16
val, wt = zip(*sorted(zip(val, wt)))
print(knapsack(W, wt, val))

90


In [35]:
def assign_code(nodes, label, result, prefix = ''):    
    childs = nodes[label]     
    tree = {}
    if len(childs) == 2:
        tree['0'] = assign_code(nodes, childs[0], result, prefix+'0')
        tree['1'] = assign_code(nodes, childs[1], result, prefix+'1')     
        return tree
    else:
        result[label] = prefix
        return label

def Huffman_code(_vals):    
    vals = _vals.copy()
    nodes = {}
    for n in vals.keys(): 
        nodes[n] = []

    while len(vals) > 1: 
        s_vals = sorted(vals.items(), key=lambda x:x[1]) 
        a1 = s_vals[0][0]
        a2 = s_vals[1][0]
        vals[a1+a2] = vals.pop(a1) + vals.pop(a2)
        nodes[a1+a2] = [a1, a2]        
    code = {}
    root = a1+a2
    tree = {}
    tree = assign_code(nodes, root, code)        
    return code

In [36]:
freq = [(0.166, 'a'), (0.166, 'b'), (0.166, 'c'), (0.666, 'd'),
(0.166, 'e'),(0.166, 'f')]    
vals = {l:v for (v,l) in freq}
print(vals)
code= Huffman_code(vals)

{'a': 0.166, 'b': 0.166, 'c': 0.166, 'd': 0.666, 'e': 0.166, 'f': 0.166}


In [73]:
#kmp
def KMPSearch(pat, txt): 
    M = len(pat) 
    N = len(txt) 
  
    
    lps = [0]*M 
    j = 0 # index for pat[] 
  
    # Preprocess the pattern (calculate lps[] array) 
    computeLPSArray(pat, M, lps) 
  
    i = 0 # index for txt[] 
    while i < N: 
        if pat[j] == txt[i]: 
            i += 1
            j += 1
  
        if j == M: 
            print ("Found pattern at index " + str(i-j)) 
            j = lps[j-1] 
  
        # mismatch after j matches 
        elif i < N and pat[j] != txt[i]: 
            # Do not match lps[0..lps[j-1]] characters, 
            # they will match anyway 
            if j != 0: 
                j = lps[j-1] 
            else: 
                i += 1
  
def computeLPSArray(pat, M, lps): 
    len = 0 # length of the previous longest prefix suffix 
  
    lps[0] # lps[0] is always 0 
    i = 1
  
    # the loop calculates lps[i] for i = 1 to M-1 
    while i < M: 
        if pat[i]== pat[len]: 
            len += 1
            lps[i] = len
            i += 1
        else: 
            # This is tricky. Consider the example. 
            # AAACAAAA and i = 7. The idea is similar  
            # to search step. 
            if len != 0: 
                len = lps[len-1] 
  
                # Also, note that we do not increment i here 
            else: 
                lps[i] = 0
                i += 1
  
txt = "ABABDABACDABABCABAB"
pat = "ABABCABAB"
KMPSearch(pat, txt) 

Found pattern at index 10


In [74]:
def Rabin_Karp_Matcher(text, pattern, d, q):
    n = len(text)
    m = len(pattern)
    h = pow(d,m-1)%q
    p = 0
    t = 0
    result = []
    for i in range(m): # preprocessing
        p = (d*p+ord(pattern[i]))%q
        t = (d*t+ord(text[i]))%q
    for s in range(n-m+1): # note the +1
        if p == t: # check character by character
            match = True
            for i in range(m):
                if pattern[i] != text[s+i]:
                    match = False
                    break
            if match:
                result = result + [s]
        if s < n-m:
            t = (t-h*ord(text[s]))%q # remove letter s
            t = (t*d+ord(text[s+m]))%q # add letter s+m
            t = (t+q)%q # make sure that t >= 0
    return result
print (Rabin_Karp_Matcher ("3141592653589793", "26", 257, 11))
print (Rabin_Karp_Matcher ("xxxxx", "xx", 40999999, 999999937))

[6]
[0, 1, 2, 3]


In [76]:
#booyer moore
NO_OF_CHARS = 256
 
def badCharHeuristic(string, size):
    badChar = [-1]*NO_OF_CHARS
    for i in range(size):
        badChar[ord(string[i])] = i;  
    return badChar
 
def search(txt, pat):
    m = len(pat)
    n = len(txt)
    badChar = badCharHeuristic(pat, m)  
    s = 0
    while(s <= n-m):
        j = m-1
        while j>=0 and pat[j] == txt[s+j]:
            j -= 1
        if j<0:
            print("Pattern occur at shift = {}".format(s))
            s += (m-badChar[ord(txt[s+m])] if s+m<n else 1)
        else:
            s += max(1, j-badChar[ord(txt[s+j])])
 
 
# Driver program to test above function
def main():
    txt = "ABAAABCD"
    pat = "ABC"
    search(txt, pat)
 
if __name__ == '__main__':
    main() 


Pattern occur at shift = 4


In [77]:
#radix
import time
starting=time.time()
from random import randint
a=[randint(1,99)for p in range(0,10)]
max1=max(a)
exp=10
numbers=[]
while max1/exp>0:
    for i in range (0,len(a)-1):
        if ((a[i]%exp)>a[i+1]%exp):
            a[i],a[i+1]=a[i+1],a[i]
    exp*=10
a

[11, 11, 29, 46, 51, 63, 63, 94, 96, 99]