In [4]:
#bubble sort
import numpy as np
import time
import random
n=int(input("Enter the number of inputs"))
a=[random.randint(0,100) for i in range(n)]
s=time.time()
print(a)
for i in range(0,n):
    for j in range(n-i-1):
        if a[j]>a[j+1]:
            temp=a[j+1]
            a[j+1]=a[j]
            a[j]=temp
    print(a)
end=time.time()
print(end-s)
print(a)

Enter the number of inputs3
[95, 91, 80]
[91, 80, 95]
[80, 91, 95]
[80, 91, 95]
0.0
[80, 91, 95]


In [3]:

#selection sort
import random
import time
size=int(input("enter the size"))
arr=[random.randint(0,100) for i in range(size)]
sta=time.time()
for i in range(0,len(arr)):
    min=i
    for j in range(i+1,len(arr)):
        if arr[min]>arr[j]:
            min=j   
    temp=arr[i]
    arr[i]=arr[min]
    arr[min]=temp
    print("sorted array",arr)
print("final array",arr)
end=time.time()
print(end-sta)

enter the size3
sorted array [21, 92, 24]
sorted array [21, 24, 92]
sorted array [21, 24, 92]
final array [21, 24, 92]
0.0


In [2]:
#binary search
def binary_search(item_list,item):
    first = 0
    last = len(item_list)-1
    found = False
    while( first<=last and not found):
        mid = (first + last)//2
        if item_list[mid] == item :
            found = True
        else:
            if item < item_list[mid]:
                last = mid - 1
            else:
                first = mid + 1	
    return found
    
print(binary_search([1,2,3,5,8], 6))
print(binary_search([1,2,3,5,8], 5))

False
True


In [1]:
#linear search:
import random
import time
def search(arr, n, x): 
  
    for i in range (0, n): 
        if (arr[i] == x): 
            return i; 
    return -1; 
  
# Driver Code 
size=int(input("enter the no of inputs"))
arr = [random.randint(0,100)for i in range(size)]
print(arr)
x = 10;  
result = search(arr,size, x) 
if(result == -1): 
    print("Element is not present in array") 
else: 
    print("Element is present at index", result); 


enter the no of inputs3
[17, 69, 17]
Element is not present in array


In [5]:
#insertion
import time
import numpy as np
import random
s=time.time()
def insertionSort(arr): 
    for i in range(1, len(arr)): 
        key = arr[i] 
        j = i-1
        while j >=0 and key < arr[j] : 
                arr[j+1] = arr[j] 
                j -= 1 
                arr[j+1] = key 
                print(arr)

arr=np.random.randint(0,100,5)
insertionSort(arr) 
e=time.time()
print(e-s)
print ("Sorted array is:") 
print(arr)


[28 43 58 21 83]
[28 43 21 58 83]
[28 21 43 58 83]
[21 28 43 58 83]
0.0
Sorted array is:
[21 28 43 58 83]


In [6]:
#quick sort
start=time.time()
def partition(arr,low,high): 
    i = ( low-1 )         # index of smaller element 
    pivot = arr[high]     # pivot 
  
    for j in range(low , high): 
  
        # If current element is smaller than or 
        # equal to pivot 
        if   arr[j] <= pivot: 
          
            # increment index of smaller element 
            i = i+1 
            arr[i],arr[j] = arr[j],arr[i] 
  
    arr[i+1],arr[high] = arr[high],arr[i+1] 
    return ( i+1 )
end=time.time()
print(start-end)
  
def quickSort(arr,low,high): 
    if low < high: 
  
        # pi is partitioning index, arr[p] is now 
        # at right place 
        pi = partition(arr,low,high) 
  
        # Separately sort elements before 
        # partition and after partition 
        quickSort(arr, low, pi-1) 
        quickSort(arr, pi+1, high) 

# Driver code to test above 
size=int(input("enter the size"))
arr = [random.randint(0,100)for i in range(size)]
print(arr)
quickSort(arr,0,size-1) 
print ("Sorted array is:") 
for i in range(size): 
    print ("%d" %arr[i])

0.0
enter the size3
[29, 52, 87]
Sorted array is:
29
52
87


In [ ]:
def insertionSort(arr): 
  
    # Traverse through 1 to len(arr) 
    for i in range(1, len(arr)): 
  
        key = arr[i] 
  
        # Move elements of arr[0..i-1], that are 
        # greater than key, to one position ahead 
        # of their current position 
        j = i-1
        while j >= 0 and key < arr[j] : 
                arr[j + 1] = arr[j] 
                j -= 1
        arr[j + 1] = key 
  
  
# Driver code to test above 
arr = [12, 11, 13, 5, 6] 
insertionSort(arr) 
for i in range(len(arr)): 
    print ("% d" % arr[i])

In [1]:
import time
starting=time.time()
from random import randint
a=[randint(1,99)for p in range(0,100)]
max1=max(a)
exp=10
numbers=[]
while max1/exp>0:
    for i in range (0,len(a)-1):
        if ((a[i]%exp)>a[i+1]%exp):
            a[i],a[i+1]=a[i+1],a[i]
    exp*=10
a

[1,
 2,
 5,
 5,
 5,
 6,
 8,
 9,
 10,
 10,
 12,
 13,
 13,
 13,
 15,
 17,
 18,
 19,
 22,
 23,
 23,
 25,
 27,
 27,
 28,
 28,
 29,
 29,
 31,
 32,
 32,
 33,
 33,
 33,
 34,
 35,
 35,
 35,
 36,
 36,
 37,
 40,
 41,
 42,
 42,
 43,
 44,
 50,
 50,
 52,
 56,
 57,
 58,
 58,
 63,
 64,
 65,
 67,
 68,
 69,
 69,
 71,
 71,
 72,
 72,
 74,
 75,
 76,
 77,
 77,
 77,
 77,
 79,
 80,
 81,
 82,
 82,
 83,
 83,
 83,
 85,
 86,
 86,
 88,
 89,
 90,
 91,
 91,
 91,
 92,
 93,
 93,
 95,
 96,
 97,
 98,
 99,
 99,
 99,
 99]