In [3]:
import time
#selection sort
import random
import time
size=int(input("enter the size"))
arr=[random.randint(0,100) for i in range(size)]
sta=time.time()
for i in range(0,len(arr)):
    min=i
    for j in range(i+1,len(arr)):
        if arr[min]>arr[j]:
            min=j   
    temp=arr[i]
    arr[i]=arr[min]
    arr[min]=temp
    print("sorted array",arr)
print("final array",arr)
end=time.time()
print(end-sta)

enter the size6
sorted array [4, 71, 97, 75, 19, 28]
sorted array [4, 19, 97, 75, 71, 28]
sorted array [4, 19, 28, 75, 71, 97]
sorted array [4, 19, 28, 71, 75, 97]
sorted array [4, 19, 28, 71, 75, 97]
sorted array [4, 19, 28, 71, 75, 97]
final array [4, 19, 28, 71, 75, 97]
0.0


In [4]:
import time
import numpy as np
#bubble sort
arr=np.random.randint(0,100,5)
size=len(arr)
sta=time.time()
for i in range(0,size):
    
    for j in range(0,size-i-1):
        if arr[j]>arr[j+1]:
            temp=arr[j+1]
            arr[j+1]=arr[j]
            arr[j]=temp
        print(arr)
end=time.time()
print(arr)
print(end-sta)

[19 26 67 37 82]
[19 26 67 37 82]
[19 26 37 67 82]
[19 26 37 67 82]
[19 26 37 67 82]
[19 26 37 67 82]
[19 26 37 67 82]
[19 26 37 67 82]
[19 26 37 67 82]
[19 26 37 67 82]
[19 26 37 67 82]
0.009038448333740234


In [7]:
#linear search
import time
import numpy as np
start=time.time()
def linear(arr,n,x):
    for i in range(0,n):
        if arr[i]==x:
            return i
    return -1
size=int(input("enter the size"))
arr=[random.randint(0,100) for i in range(size)]
print(arr)
x=2
n=len(arr)
result=linear(arr,n,x)
if (result==-1):
    print("no")
else:
    print("yes",result)
end=time.time()
print(end-start)

enter the size5
[60, 30, 7, 83, 81]
no
1.4383940696716309


In [8]:
#insertion
import time
import numpy as np
start=time.time()
def insertion(arr):
    for i in range(1,len(arr)):
        key=arr[i]
        j=i-1
        while j>=0 and key<arr[j]:
            arr[j+1]=arr[j]
            j-=1
            arr[j+1]=key
            print(arr)
arr=np.random.randint(0,100,5)
print(arr)
result=insertion(arr)
end=time.time()
print(end-start)


[32 96 51 68 29]
[32 51 96 68 29]
[32 51 68 96 29]
[32 51 68 29 96]
[32 51 29 68 96]
[32 29 51 68 96]
[29 32 51 68 96]
0.0


In [9]:
def partition(array,first,last):
    left=first+1
    right=last
    pivot=array[first]
    while True:
        while  left<=right and array[right]>=pivot :
            right=right-1
        while  left<=right and array[left]<=pivot:
            left=left+1
        if left<right:
            array[left],array[right]=array[right],array[left]
        else:
            break
    array[first],array[right]=array[right],array[first]
    return right


In [10]:
def quicksort(array,low,up):
    if low >= up:
        return
    p=partition(array,low,up)
    quicksort(array,low,p-1)
    quicksort(array,p+1,up)
    

In [12]:
size=int(input("enter the size"))
array = [random.randint(0,100)for i in range(size)]
print(array)
quicksort(array, 0, len(array) - 1)
print(array)

enter the size5
[39, 39, 34, 64, 18]
[18, 34, 39, 39, 64]


In [ ]:
#binary
def binary(item_list,item):
    first=0
    last=len(item_list)-1
    found=False
    while(first<=last and not found):
        mid=(first+last)//2
        if item_list[mid]==item:
            found=True
        else:
            if item_list[mid]>item:
                last=mid-1
            else:
                first=mid+1
    return found

print(binary([1,2,3,5,8], 6))

In [ ]:
#merge sort
import numpy as np
import time
import random
size=int(input("Enter the number of inputs"))
l=[random.randint(0,100) for i in range(size)]
s=time.time()
def mergesort(list):
    if len(list)>1:
        mid=len(list)//2
        left=list[:mid]
        right=list[mid:]
        mergesort(left)
        mergesort(right)
        merge(list,left,right)
def merge(list,left,right):
    if len(list)>1:
        while i <len(left)and j <len(right):
            if left[i]<right[j]:
                list[k]=left[i]
                i=i+1
            else:
                list[k]=right[j]
                j=j+1
            k=k+1
            while i<len(left):
                list[k]=left[i]
                i=i+1
                k=k+1
            while j<len(right):
                list[k]=right[j]
                j=j+1
                k=k+1
            print("merging",list)
mergesort(l)
print("time:{ime.time()-s}")

In [ ]:
#bucket sort
def insertionsort(b):
    for i in range(1,len(b)):
        temp=b[i]
        j=i-1
        while j>=0 and b[j]>temp:
            b[j+1]=b[j]
            j=j-1
        b[j+1]=temp
    return b
def bucketsort(n):
    arr=[]
    slot_num=10
    for i in range(slot_num):
        arr.append([])
    for j in x:
        index_b=int(slot_num*j)
        arr[index_b].append(j)
    for i in range(slot_num):
        arr[i]=insertionsort(arr[i])
    
    k=0
    for i in range(slot_num):
        for j in range(len(arr[i])):
            x[k]=arr[i][j]
            k+=1
    return x

lists = np.random.randint(0,100,5)
print("Sorted Array is") 
print(bucketsort(lists)) 

In [ ]:
def insertionSort(b): 
    for i in range(1, len(b)): 
        up = b[i] 
        j = i - 1
        while j >=0 and b[j] > up:  
            b[j + 1] = b[j] 
            j -= 1
        b[j + 1] = up      
    return b      
              
def bucketSort(x): 
    arr = [] 
    slot_num = 10 # 10 means 10 slots, each 
                  # slot's size is 0.1 
    for i in range(slot_num): 
        arr.append([]) 
          
    # Put array elements in different buckets  
    for j in x: 
        index_b = int(slot_num * j)  
        arr[index_b].append(j) 
      
    # Sort individual buckets  
    for i in range(slot_num): 
        arr[i] = insertionSort(arr[i]) 
          
    # concatenate the result 
    k = 0
    for i in range(slot_num): 
        for j in range(len(arr[i])): 
            x[k] = arr[i][j] 
            k += 1
    return x 
  
# Driver Code 
x = np.random.randint(0,100,5)  
print("Sorted Array is") 
print(bucketSort(x)) 

In [ ]:
import numpy as np
def heapify(arr, n, i): 
    largest = i # Initialize largest as root 
    l = 2 * i + 1     # left = 2*i + 1 
    r = 2 * i + 2     # right = 2*i + 2 
  
    # See if left child of root exists and is 
    # greater than root 
    if l < n and arr[i] < arr[l]: 
        largest = l 
  
    # See if right child of root exists and is 
    # greater than root 
    if r < n and arr[largest] < arr[r]: 
        largest = r 
  
    # Change root, if needed 
    if largest != i: 
        arr[i],arr[largest] = arr[largest],arr[i] # swap 
  
        # Heapify the root. 
        heapify(arr, n, largest) 
  
# The main function to sort an array of given size 
def heapSort(arr): 
    n = len(arr) 
  
    # Build a maxheap. 
    for i in range(n, -1, -1): 
        heapify(arr, n, i) 
  
    # One by one extract elements 
    for i in range(n-1, 0, -1): 
        arr[i], arr[0] = arr[0], arr[i] # swap 
        heapify(arr, i, 0) 
  
# Driver code to test above 
arr = np.random.randint(0,100,5)
print()
heapSort(arr) 
n = len(arr) 
print ("Sorted array is") 
for i in range(n): 
    print ("%d" %arr[i])

In [ ]:
import time
import random
size=int(input("Enter the number of inputs"))
l=[random.randint(0,100) for i in range(size)]
s=time.time()
def mergeSort(list):
    print("splitting",list)
    if len(list)>1:
        mid = len(list)//2
        left = list[:mid]
        right = list[mid:]
        mergeSort(left)
        mergeSort(right)
        merge(list,left,right)
def merge(list,left,right):
    if len(list)>1:
        i=j=k=0      
        while i < len(left) and j < len(right):
            if left[i] < right[j]:
                list[k]=left[i]
                i=i+1
            else:
                list[k]=right[j]
                j=j+1
            k=k+1
        while i < len(left):
            list[k]=left[i]
            i=i+1
            k=k+1
        while j < len(right):
            list[k]=right[j]
            j=j+1
            k=k+1
    print("Merging ",list)
mergeSort(l)
print(f"Execution time :{time.time()-s}")

import numpy as np
import time
import random
size=int(input("Enter the number of inputs"))
l=[random.randint(0,100) for i in range(size)]
s=time.time()
def mergesort(arr): 
    if len(arr) >1: 
        mid = len(arr)//2 #Finding the mid of the array 
        L = arr[:mid] # Dividing the array elements  
        R = arr[mid:] # into 2 halves 
  
        mergeSort(L) # Sorting the first half 
        mergeSort(R) # Sorting the second half 
  
        i = j = k = 0
          
        # Copy data to temp arrays L[] and R[] 
        while i < len(L) and j < len(R): 
            if L[i] < R[j]: 
                arr[k] = L[i] 
                i+=1
            else: 
                arr[k] = R[j] 
                j+=1
            k+=1
          
        # Checking if any element was left 
        while i < len(L): 
            arr[k] = L[i] 
            i+=1
            k+=1
          
        while j < len(R): 
            arr[k] = R[j] 
            j+=1
            k+=1
mergesort(l)

print(f"Execution time :{time.time()-s}")

In [ ]:
import numpy as np
import time
import random
size=int(input("Enter the number of inputs"))
l=[random.randint(0,100) for i in range(size)]
s=time.time()
def mergesort(list):
    if len(list)>1:
        mid=len(list)//2
        left=list[:mid]
        right=list[mid:]
        mergesort(left)
        mergesort(right)
        merge(list,left,right)
def merge(list,left,right):
    if len(list)>1:
        while i <len(left)and j <len(right):
            if left[i]<right[j]:
                list[k]=left[i]
                i=i+1
            else:
                list[k]=right[j]
                j=j+1
            k=k+1
            while i<len(left):
                list[k]=left[i]
                i=i+1
                k=k+1
            while j<len(right):
                list[k]=right[j]
                j=j+1
                k=k+1
            print("merging",list)
mergesort(l)
print("time:{ime.time()-s}")

In [ ]:
def partition(arr,low,high): 
    i = ( low-1 )       
    pivot = arr[high]      
    for j in range(low , high): 
        if   arr[j] < pivot: 
            i = i+1 
            arr[i],arr[j] = arr[j],arr[i] 
    arr[i+1],arr[high] = arr[high],arr[i+1] 
    return ( i+1 )  
def quickSort(arr,low,high): 
    if low < high: 
        pi = partition(arr,low,high) 
        quickSort(arr, low, pi-1) 
        quickSort(arr, pi+1, high) 
  
# Driver code:
arr = [10, 7, 8, 9, 1, 5] 
n = len(arr) 
quickSort(arr,0,n-1) 
print ("Sorted array is:") 
for i in range(n): 
    print ("%d" %arr[i])



In [21]:
import time
starting=time.time()
from random import randint
a=[randint(1,99)for p in range(0,200)]
max1=max(a)
exp=10
numbers=[]
while max1/exp>0:
    for i in range (0,len(a)-1):
        if ((a[i]%exp)>a[i+1]%exp):
            a[i],a[i+1]=a[i+1],a[i]
    exp*=10
print(a)
ending=time.time()
print(ending-starting)

[1, 1, 2, 2, 3, 4, 5, 6, 6, 6, 7, 8, 9, 9, 11, 11, 12, 12, 12, 12, 14, 14, 14, 15, 15, 15, 15, 15, 17, 17, 17, 18, 20, 20, 21, 21, 22, 22, 23, 23, 23, 24, 25, 26, 26, 27, 27, 27, 27, 28, 28, 28, 29, 29, 29, 29, 29, 31, 32, 33, 33, 33, 33, 34, 34, 35, 35, 36, 36, 36, 38, 38, 39, 40, 41, 42, 42, 43, 43, 43, 43, 44, 44, 44, 44, 44, 44, 45, 45, 45, 46, 46, 46, 46, 47, 48, 48, 49, 49, 49, 50, 50, 51, 51, 51, 52, 52, 52, 53, 53, 54, 54, 55, 55, 56, 57, 57, 57, 57, 58, 59, 59, 60, 60, 61, 62, 62, 62, 62, 63, 64, 64, 64, 64, 65, 66, 66, 67, 67, 67, 68, 68, 68, 68, 69, 69, 70, 70, 71, 71, 72, 72, 73, 73, 73, 74, 74, 74, 74, 75, 75, 76, 76, 77, 78, 80, 80, 80, 81, 81, 82, 84, 84, 85, 85, 85, 86, 86, 88, 89, 89, 89, 89, 90, 90, 90, 91, 91, 92, 93, 94, 94, 95, 95, 95, 96, 97, 98, 98, 99]
0.024001598358154297
